module.exports = {
  attributes: {
    // ==========================================
    // Core Relation
    // ==========================================
    followUp: { model: 'followup', required: true },

    // ==========================================
    // Action Details
    // ==========================================
    action: { 
      type: 'string', 
      required: true,
      // NOTE: 'isIn' is intentionally removed here because your 
      // FollowUpsController currently passes dynamic sentences 
      // (e.g., "Extended by 5 days...") directly into this field.
    },

    // ==========================================
    // Actor Information
    // ==========================================
    performedBy: { model: 'user', required: true },
    performedByRole: { 
      type: 'string',
      description: 'The role of the user at the time of the action' 
    },

    // ==========================================
    // State Changes (Delta)
    // ==========================================
    oldValue: { type: 'json' },
    newValue: { type: 'json' },

    // ==========================================
    // Context & Timestamps
    // ==========================================
    metadata: { type: 'json' },
    timestamp: { type: 'string' }
  },

  // ==========================================
  // Dynamic UI Formatter
  // ==========================================
  customToJSON: function() {
    // 1. Setup defaults
    let displayAction = this.action || 'System Action';
    let displayDescription = 'A system action was recorded.';

    // 2. Intercept and format the exact strings generated by FollowUpsController.js
    if (this.action === 'FOLLOW_UP_CLOSED') {
      displayAction = 'Follow-Up Closed';
      displayDescription = 'The follow-up case was successfully closed.';
    } 
    else if (this.action === 'FOLLOW_UP_REOPENED') {
      displayAction = 'Follow-Up Reopened';
      displayDescription = 'The follow-up case was reopened for further monitoring.';
    } 
    else if (this.action?.startsWith('Extended by')) {
      displayAction = 'Deadline Extended';
      displayDescription = this.action; // Passes the full "Extended by X days..." string
    } 
    else if (this.action?.startsWith('SPECIALIST_CHANGED:')) {
      displayAction = 'Specialist Reassigned';
      displayDescription = this.action.replace('SPECIALIST_CHANGED: ', ''); // Strips the prefix
    } 
    else if (this.action?.startsWith('CONSULTATION_SCHEDULED:')) {
      displayAction = 'Consultation Scheduled';
      displayDescription = this.action.replace('CONSULTATION_SCHEDULED: ', ''); // Strips the prefix
    }

    // 3. Output the properly mapped object to the frontend
    return {
      ...this,
      action: displayAction,       // Maps to <Text style={styles.actionText}>
      description: displayDescription // Maps to <Text style={styles.descText}>
    };
  }
};